version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_version_db
    volumes:
      - "./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
      - "./postgres:/var/lib/postgresql/data"
    networks:
      net_interna:
        aliases:
          - net_prueba_tecnica_postgres

volumes:
  postgres: {}

networks:
  net_interna:
    name: net_prueba_tecnica
    driver: bridge
    ipam:
      driver: default